<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>
<body>
    <!-- Adding a converter because i couldn't let the user with only date in unix / epoch will be delete As soon as i can get the chart to work -->
    <h1>Converted Unix/Epoch date to human readable date (yyyy-dd-mm + h-min-sec)</h1>
    <p class="epochtime"><?php echo $dt->format('Y-m-d H:i:s'); ?></p>
    <a href="dashboard.php">Get back to the main page ?</a>
</body>
</html>