<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta http-equiv="refresh" content="30"> -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <title>Dashboard crypto-currencies</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Crypto Currencies DashBoard</h1>
    <form action="getcurrency.php" method="post" id="cryptoCurrency">
        <label for="cryptoCurrency">I want to see the chart of :</label>
        <select name="cryptoCurrency">
            <option value="bitcoin">Bitcoin</option>
            <option value="ethereum">Ethereum</option>
            <option value="ripple">XRP</option>
            <option value="tether">Tether</option>
            <option value="chainlink">Chainlink</option>
            <option value="bitcoin-cash">Bitcoin cash</option>
            <option value="litecoin">Litecoin</option>
            <option value="stellar">Stellar</option>
            <option value="dogecoin">Dogecoin</option>
            <option value="masternet">Masternet</option>
            <option value="tagcoin">Tagcoin</option>
            <option value="waves">Waves</option>
            <option value="zillioncoin">Zillioncoin</option>
            <option value="quant-network">Quant</option>
            <option value="maker">Maker</option>
            <option value="true-usd">tusd</option>
            <option value="tsingzou-tokyo-medical-cooperation">Tsingzou-Tokyo Medical Cooperation</option>
            <option value="txt">TXT</option>
            <option value="udap">Udap</option>
            <option value="botton">Botton</option>
            <option value="nxm">Nxm</option>
            <option value="omisego">OMG Network</option>
            <option value="travel1click">Travel1Click</option>
            <option value="42-coin">42-coin</option>
            <option value="thorchain">Thorchain</option>
            <option value="numeraire">Numeraire</option>
            <option value="ravencoin">Ravencoin</option>
            <option value="gatechain-token">Gatechain Token</option>
            <option value="kusama">Kusama</option>
            <option value="monacoin">MonaCoin</option>
            <option value="hyperion">Hyperion</option>
            <!-- we can add as much option as we want if we got the ID of the crypto we want  -->
        </select>
        <label>in</label>
        <input type="radio" id="currency" name="currency" value="usd" require>
        <label for="usd">Usd</label>
        <input type="radio" id="currency" name="currency" value="eur">
        <label for="eur">Euro</label>
        <input type="radio" id="currency" name="currency" value="rub">
        <label for="rub">Rub</label>
        <input type="submit" id="submit">
    </form>
    <img src="bitcoin.jpg" alt="Bitcoin logo">
</body>
</html>